services:
  database:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=doqmt
      - MYSQL_PASSWORD=1234
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3306:3306
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/backup:/var/lib/mysql
    networks:
      - net

  application:
    depends_on:
      - database
    build: .
    restart: always
    ports:
      - 80:80
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/test?useSSL=false
      SPRING_DATASOURCE_USERNAME: doqmt
      SPRING_DATASOURCE_PASSWORD: 1234
      EMAIL: doqmt.0@gmail.com
      PASSWORD: gxbajrpyrunmfkzq
    networks:
      - net

networks:
  net: