server:
  port: 443
  ssl:
    enabled: true
    keyStore: classpath:keystore.p12
    keyStorePassword: qwe123!@#
    keyStoreType: PKCS12

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none