server:
  port: 8080
  
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/doqmt
    username: doqmt
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create